### ISSUE TITLE
`Make test` fails

### ISSUE THREAD

**Issue by lbarman** [vaultage-pm/vaultage#189]
```
> vaultage@0.0.0 lint /home/jwhite/d/git/vaultage/packages/vaultage
> tslint -p .

 PASS  test/unit/JSONDatabase.spec.ts
 PASS  test/unit/VaultageServer.spec.ts
 PASS  test/integration/web-ui.spec.ts (19.339s)
-------------------------|----------|----------|----------|----------|-------------------|
File                     |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
-------------------------|----------|----------|----------|----------|-------------------|
All files                |      100 |    79.55 |      100 |      100 |                   |
 src                     |      100 |      100 |      100 |      100 |                   |

        Failed to write coverage reports:
        ERROR: TypeError: metrics.isEmpty is not a function
        STACK: TypeError: metrics.isEmpty is not a function
    at tableRow (/home/jwhite/d/git/vaultage/packages/vaultage/node_modules/istanbul-reports/lib/text/index.js:133:27)
    at TextReport.onSummary (/home/jwhite/d/git/vaultage/packages/vaultage/node_modules/istanbul-reports/lib/text/index.js:188:15)
    at TextReport.onDetail (/home/jwhite/d/git/vaultage/packages/vaultage/node_modules/istanbul-reports/lib/text/index.js:193:17)
    at Visitor.(anonymous function) [as onDetail] (/home/jwhite/d/git/vaultage/packages/vaultage/node_modules/istanbul-lib-report/lib/tree.js:34:30)
    at ReportNode.Node.visit (/home/jwhite/d/git/vaultage/packages/vaultage/node_modules/istanbul-lib-report/lib/tree.js:123:17)
    at /home/jwhite/d/git/vaultage/packages/vaultage/node_modules/istanbul-lib-report/lib/tree.js:116:23
    at Array.forEach (<anonymous>)
    at visitChildren (/home/jwhite/d/git/vaultage/packages/vaultage/node_modules/istanbul-lib-report/lib/tree.js:115:32)
    at ReportNode.Node.visit (/home/jwhite/d/git/vaultage/packages/vaultage/node_modules/istanbul-lib-report/lib/tree.js:126:5)
    at /home/jwhite/d/git/vaultage/packages/vaultage/node_modules/istanbul-lib-report/lib/tree.js:116:23
```

**Comment by hmil** [comment]
This is just a warning. Something wrong with the coverage, it's not causing the test to fail.

**Comment by lbarman** [comment]
OK, closing.
