### ISSUE TITLE
Pupeteer Failure

### ISSUE THREAD

**Issue by lbarman** [vaultage-pm/vaultage#191]
```
 RUNS  test/integration/web-ui.spec.ts
 RUNS  test/unit/VaultageServer.spec.ts
 PASS  test/unit/JSONDatabase.spec.ts
 PASS  test/unit/VaultageServer.spec.ts
 FAIL  test/integration/web-ui.spec.ts (7.254s)
  ● Commands of the web UI › auth

    expect(received).toMatch(expected)

    Expected value to match:
      /Pull OK/
    Received:
      ""

      55 |     test('auth', async () => {
      56 |         await model.login('john', '1234');
    > 57 |         expect(await model.getLogContents()).toMatch(/Pull OK/);
         |                                              ^
      58 |     });
      59 | 
      60 |     test('clear', async () => {

      at Object.<anonymous> (test/integration/web-ui.spec.ts:57:46)
      at step (test/integration/web-ui.spec.ts:73:23)
      at Object.next (test/integration/web-ui.spec.ts:40:20)
      at fulfilled (test/integration/web-ui.spec.ts:7:32)

  ● Commands of the web UI › add

    expect(received).toMatch(expected)

    Expected value to match:
      /Push OK/
    Received:
      ""

      71 |         await model.type('some p@ssword');
      72 |         await model.type('http://some-url');
    > 73 |         expect(await model.getLogContents()).toMatch(/Push OK/);
         |                                              ^
      74 | 
      75 |         await model.type('clear');
      76 |         await model.type('ls');

      at Object.<anonymous> (test/integration/web-ui.spec.ts:73:46)
      at step (test/integration/web-ui.spec.ts:73:23)
      at Object.next (test/integration/web-ui.spec.ts:40:20)
      at fulfilled (test/integration/web-ui.spec.ts:7:32)

  ● Commands of the web UI › gen

    expect(received).toMatch(expected)

    Expected value to match:
      /Push OK/
    Received:
      ""

      92 |         await model.type('some username');
      93 |         await model.type('http://some-url');
    > 94 |         expect(await model.getLogContents()).toMatch(/Push OK/);
         |                                              ^
      95 | 
      96 |         await model.type('clear');
      97 |         await model.type('ls');

      at Object.<anonymous> (test/integration/web-ui.spec.ts:94:46)
      at step (test/integration/web-ui.spec.ts:73:23)
      at Object.next (test/integration/web-ui.spec.ts:40:20)
      at fulfilled (test/integration/web-ui.spec.ts:7:32)

  ● Commands of the web UI › edit

    There are no entries to remove

      113 |         const table = await model.readEntryTable();
      114 |         if (table.length === 0) {
    > 115 |             throw new Error('There are no entries to remove');
          |                   ^
      116 |         }
      117 |         const id = table[0].id;
      118 | 

      at Object.<anonymous> (test/integration/web-ui.spec.ts:115:19)
      at step (test/integration/web-ui.spec.ts:73:23)
      at Object.next (test/integration/web-ui.spec.ts:40:20)
      at fulfilled (test/integration/web-ui.spec.ts:7:32)

  ● Commands of the web UI › rm

    There are no entries to remove

      159 |         const table = await model.readEntryTable();
      160 |         if (table.length === 0) {
    > 161 |             throw new Error('There are no entries to remove');
          |                   ^
      162 |         }
      163 |         const id = table[0].id;
      164 | 

      at Object.<anonymous> (test/integration/web-ui.spec.ts:161:19)
      at step (test/integration/web-ui.spec.ts:73:23)
      at Object.next (test/integration/web-ui.spec.ts:40:20)
      at fulfilled (test/integration/web-ui.spec.ts:7:32)

  ● Commands of the web UI › logout

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      194 | 
      195 |         await model.type('ls');
    > 196 |         expect(await model.hasError()).toBe(true);
          |                                        ^
      197 |     });
      198 | 
      199 |     test('pull', async () => {

      at Object.<anonymous> (test/integration/web-ui.spec.ts:196:40)
      at step (test/integration/web-ui.spec.ts:73:23)
      at Object.next (test/integration/web-ui.spec.ts:40:20)
      at fulfilled (test/integration/web-ui.spec.ts:7:32)
```

**Comment by lbarman** [comment]
It seems that the interaction with the page is broken. Even after calling `page.keyboard.type(xxx)` and trying to login, the page content is still:
```
      <!DOCTYPE html><html xmlns="http://www.w3.org/1999/xhtml"><head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <meta http-equiv="X-UA-Compatible" content="ie=edge">
          <title>Vaultage</title>
          <link rel="icon" type="image/png" href="favicon.png">
          <link rel="stylesheet" href="main.css">
      </head>
      <body onload="webcli.start(document.body)">
          <script src="dist/vaultage.js"></script>
          <script src="dist/main.js"></script>
      
      
      </body></html>
```
That is, no javascript seems executed
